### ISSUE TITLE
Release a tag v1.0.0 in Github

### ISSUE THREAD

**Issue by pedrofurtado** [shirts/microsoft-teams-ruby#2]
Hi @shirts @abumerijana !

Could you please release a tag, in repo when you have time, for v1.0.0 (already published in RubyGems) in order to keep synced the version and source code?

Thanks a lot! 🍻

**Comment by shirts** [comment]
Done https://github.com/shirts/microsoft-teams-ruby/releases/tag/v1.0.0

**Comment by pedrofurtado** [comment]
Thanks a lot @shirts ! And thank you for your great work on this gem 🍻
